# Generated by Django 5.2.17 on 2026-09-10 07:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(editable=False, unique=True)),
                ('key', models.CharField(db_index=True, editable=False, max_length=24, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, max_length=120)),
                ('component', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=16)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='P2', max_length=4)),
                ('tester_status', models.CharField(choices=[('open', 'Open'), ('under-review', 'Under Review'), ('verified', 'Verified'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='open', max_length=16)),
                ('developer_status', models.CharField(choices=[('backlog', 'Backlog'), ('assigned', 'Assigned'), ('in-progress', 'In Progress'), ('ready-for-qa', 'Ready for QA'), ('fixed', 'Fixed'), ('blocked', 'Blocked')], default='backlog', max_length=16)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], default='production', max_length=16)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('device', models.CharField(blank=True, max_length=120)),
                ('os', models.CharField(blank=True, max_length=120)),
                ('sprint', models.CharField(blank=True, max_length=60)),
                ('labels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('steps_to_reproduce', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('expected_result', models.TextField(blank=True)),
                ('actual_result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bugs', to='projects.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_bugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('moved', 'Moved'), ('assigned', 'Assigned'), ('status', 'Status'), ('severity', 'Severity'), ('priority', 'Priority'), ('comment', 'Comment'), ('attachment', 'Attachment'), ('fixed', 'Fixed'), ('verified', 'Verified'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=16)),
                ('summary', models.CharField(max_length=300)),
                ('from_value', models.CharField(blank=True, max_length=160, null=True)),
                ('to_value', models.CharField(blank=True, max_length=160, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='bugs.bug')),
            ],
            options={
                'verbose_name_plural': 'activity',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bugs.bug')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bugs.comment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('recording', 'Screen recording'), ('pdf', 'PDF'), ('archive', 'Archive'), ('log', 'Log file'), ('file', 'File')], default='file', max_length=16)),
                ('size', models.BigIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bugs.bug')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bugs.comment')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='bugs.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['tester_status'], name='bugs_bug_tester__1ac74f_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['developer_status'], name='bugs_bug_develop_520791_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['severity'], name='bugs_bug_severit_9ad1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['priority'], name='bugs_bug_priorit_4a3773_idx'),
        ),
        migrations.AddIndex(
            model_name='bug',
            index=models.Index(fields=['project', '-created_at'], name='bugs_bug_project_2900e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('comment', 'user', 'emoji'), name='unique_reaction_per_user'),
        ),
    ]
