# Generated by Django 5.2.17 on 2026-09-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bug_number_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/%Y/%m/'),
        ),
    ]
